groups:
- name: goroutines_monitoring
  rules:
  - alert: TooMuchGoroutines
    expr: go_goroutines{job="prometheus"} > 35
    for: 5m
    labels:
      cat: "thread"
    annotations:
      summary: "too much goroutines of job prometheus."
      description: "test desc"

- name: go_threads_monitoring
  rules:
  - alert: TooMuchGoThreads
    expr: go_threads > 20
    labels:
      cat: "thread"
    annotations:
      summary: "too much go thread of job prometheus"
      description: "testing"
